### ISSUE TITLE
KeyError: '-1008' when setting saturation to larger than 100

### ISSUE THREAD

**Issue by MonicaisHer** [farshidtz/matter-bridge-tapo#2]
Please refer to the details on the PyP100 package side: https://github.com/fishbigger/TapoP100/issues/110

```
$ sudo chip-tool colorcontrol move-to-saturation 200 0 0 0 110 1
(No error)
```
```
$ journalctl -f | grep matter-bridge-tapo-lighting
Apr 18 15:32:31 ubuntu matter-bridge-tapo-lighting.tapo-bridge[144089]: Exception ignored on calling ctypes callback function: <function attributeChangeCallback at 0x7f688f5f3f40>
Apr 18 15:32:31 ubuntu matter-bridge-tapo-lighting.tapo-bridge[144089]: Traceback (most recent call last):
Apr 18 15:32:31 ubuntu matter-bridge-tapo-lighting.tapo-bridge[144089]:   File "/snap/matter-bridge-tapo-lighting/1/bin/lighting.py", line 134, in attributeChangeCallback
Apr 18 15:32:31 ubuntu matter-bridge-tapo-lighting.tapo-bridge[144089]:     set_saturation(value[0])
Apr 18 15:32:31 ubuntu matter-bridge-tapo-lighting.tapo-bridge[144089]:   File "/snap/matter-bridge-tapo-lighting/1/bin/lighting.py", line 87, in set_saturation
Apr 18 15:32:31 ubuntu matter-bridge-tapo-lighting.tapo-bridge[144089]:     dev.setColor(hue, saturation)
Apr 18 15:32:31 ubuntu matter-bridge-tapo-lighting.tapo-bridge[144089]:   File "/snap/matter-bridge-tapo-lighting/1/connectedhomeip/python_env/lib/python3.10/site-packages/PyP100/PyL530.py", line 109, in setColor
Apr 18 15:32:31 ubuntu matter-bridge-tapo-lighting.tapo-bridge[144089]:     errorMessage = self.errorCodes[str(errorCode)]
Apr 18 15:32:31 ubuntu matter-bridge-tapo-lighting.tapo-bridge[144089]: KeyError: '-1008'
Apr 18 15:32:31 ubuntu matter-bridge-tapo-lighting.tapo-bridge[144089]: [1681824751.710664][144089:144098] CHIP:ZCL: Hue 200 Saturation 200 endpoint 1
```

**Comment by MonicaisHer** [comment]
Upon trying to set the color temperature, the identical error code presents itself once more:
```
$ sudo chip-tool colorcontrol move-color-temperature 1 16319 0 65279 0 0 110 1
(No error)
```
```
$ journalctl -f | grep matter-bridge-tapo-lighting
Apr 19 11:11:13 ubuntu matter-bridge-tapo-lighting.tapo-bridge[190983]: Exception ignored on calling ctypes callback function: <function attributeChangeCallback at 0x7f30bb7dbf40>
Apr 19 11:11:13 ubuntu matter-bridge-tapo-lighting.tapo-bridge[190983]: Traceback (most recent call last):
Apr 19 11:11:13 ubuntu matter-bridge-tapo-lighting.tapo-bridge[190983]:   File "/snap/matter-bridge-tapo-lighting/1/bin/lighting.py", line 138, in attributeChangeCallback
Apr 19 11:11:13 ubuntu matter-bridge-tapo-lighting.tapo-bridge[190983]:     set_color_temperature(value[0])
Apr 19 11:11:13 ubuntu matter-bridge-tapo-lighting.tapo-bridge[190983]:   File "/snap/matter-bridge-tapo-lighting/1/bin/lighting.py", line 94, in set_color_temperature
Apr 19 11:11:13 ubuntu matter-bridge-tapo-lighting.tapo-bridge[190983]:     dev.setColorTemp(kelvin)
Apr 19 11:11:13 ubuntu matter-bridge-tapo-lighting.tapo-bridge[190983]:   File "/snap/matter-bridge-tapo-lighting/1/connectedhomeip/python_env/lib/python3.10/site-packages/PyP100/PyL530.py", line 74, in setColorTemp
Apr 19 11:11:13 ubuntu matter-bridge-tapo-lighting.tapo-bridge[190983]:     errorMessage = self.errorCodes[str(errorCode)]
Apr 19 11:11:13 ubuntu matter-bridge-tapo-lighting.tapo-bridge[190983]: KeyError: '-1008'
Apr 19 11:11:13 ubuntu matter-bridge-tapo-lighting.tapo-bridge[190983]: [1681895473.024545][190983:190990] CHIP:ZCL: Color Temperature 65279
```

**Comment by MonicaisHer** [comment]
The saturation setting will only function correctly if the <Saturation> value falls within the range of 1 to 100:

```
# sudo chip-tool colorcontrol move-to-saturation <Saturation> <TransitionTime> <OptionsMask> <OptionsOverride> <destination-id> <endpoint-id-ignored-for-group-commands>
sudo chip-tool colorcontrol move-to-saturation 50 0 0 0 110 1
```

**Comment by farshidtz** [comment]
So the error is really because an out of range value is being sent to the library. The following references also send larger values:
- https://github.com/project-chip/connectedhomeip/blob/b8389773bcb81b444b5ad62a68046af6f5ef4148/src/app/tests/suites/certification/Test_TC_CC_4_5.yaml#L82
- https://docs.espressif.com/projects/esp-matter/en/main/esp32/developing.html

In seems like the byte input from the controller should be mapped to 0-100 which is the value expected by the library.
